### ISSUE TITLE
Crash if the SNI isn't connected

### ISSUE THREAD

**Issue by markyys** [peroquenariz/StatsCompanion#2]
After about 15 minutes of trying to connect (displaying the message `Device not found! Make sure your device/emulator is 
correctly connected to SNI.`) it will crash with the message `A new guard page for the stack cannot be created.` it also fails to produce any crash log.

This is not a huge issue most of the time, but it's problematic in two circumstances:
a) if I want to leave Stats Companion running and have it just detect when I start a seed (not a big deal, I can just restart it)
b) if there is some problem with the SNI connection during a seed, in which case it will not properly generate the log even if I restart Stats Companion immediately.

**Comment by peroquenariz** [comment]
Thanks for the report! I've just came back from vacations so I'll take a look sometime this week. The issue is probably related to running out of memory when recursively calling the reconnect method.
